const experiences = [
  { role: 'Specialist Instrumentation', company: 'PT Amman Mineral Nusa Tenggara', date: 'Apr 2024 – Present', points: ['Copper smelter commissioning, startup support, maintenance and troubleshooting.', 'Performed interlock logic testing, DCS diagnostics, instrument validation and reliability improvement.', 'Handled control valve, MOV, burner, analyzer, gas detector, flow, pressure, temperature, conveyor and weighing system cases.'] },
  { role: 'Instrumentation Technician', company: 'PT Bhimasena Power Indonesia', date: 'Mar 2022 – Mar 2024', points: ['Coal-fired power plant commissioning and O&M support.', 'Supported shutdown activities, control loop modification, field troubleshooting and contractor coordination.', 'Hands-on with pressure/DP transmitters, flowmeters, ultrasonic/radar/GWR level, pneumatic positioners, Allen Bradley PLC and HMI systems.'] },
  { role: 'Instrumentation & Control Staff (On-Job Trainee)', company: 'Pertamina EP & Refinery Unit IV', date: '2019 – 2021', points: ['Instrumentation and control engineering support for oil & gas facilities.', 'Supported maintenance, operation, functional safety awareness, SIL-related activities, and multidisciplinary coordination.'] }
];

const skills = [
  { group: 'Field Instrumentation', items: ['Pressure / DP Transmitter', 'Temperature / RTD / Thermocouple', 'Flowmeter', 'Radar / Ultrasonic / GWR Level', 'pH / ORP / Conductivity', 'SO₂ / O₂ / Gas Analyzer'] },
  { group: 'Control & Final Element', items: ['Control Valve', 'Pneumatic Positioner', 'Motorized Valve / MOV', 'Damper Actuator', 'Burner System', 'Flame Scanner / Flame Rod'] },
  { group: 'Automation & Systems', items: ['Netmation DCS', 'Allen Bradley PLC', 'HMI / SCADA', 'DCS-PLC Interface', 'Interlock Logic', 'Historian Awareness'] },
  { group: 'Testing & Tools', items: ['HART Communicator', 'AMS Trex', 'Loop Calibrator', 'Multimeter', 'Megger', 'Signal Simulation'] },
  { group: 'Reliability & Maintenance', items: ['Root Cause Analysis', 'Preventive Maintenance', 'Corrective Maintenance', 'Calibration', 'Loop Check', 'Troubleshooting Report'] },
  { group: 'Leadership', items: ['Field Leadership', 'Operation Coordination', 'Mechanical Coordination', 'Electrical Coordination', 'PIL / Engineering Coordination', 'Technical Recommendation'] }
];

const cases = [
  {id:'001', equipment:'111-SG01-PT003', category:'Pressure', title:'Pressure Transmitter Zero Validation', issue:'Zero indication deviation under atmospheric condition.', actions:['PV before -5.431 Pa, mA before 19.985 mA','Performed zero trim','Removed plastic cap on low side port','Installed temporary plastic cover and recommended elbow connector'], result:'PV after 0.188 Pa and output 20.000 mA.'},
  {id:'002', equipment:'111-SG01-PT004', category:'Pressure', title:'Pressure Transmitter Zero Validation', issue:'Low range pressure transmitter indication error.', actions:['PV before -0.004 kPa, mA before 3.950 mA','Performed zero trim','Drained liquid inside impulse pipe','Recommended elbow connector on low side port'], result:'PV normalized to 0.000 kPa and mA 4.004 mA.'},
  {id:'003', equipment:'111-MD01-PT5.1.02', category:'Pressure', title:'Atmospheric Verification', issue:'DCS showed -4.23 kPa.', actions:['Verified actual pressure by opening drain plug','Confirmed line was vacuum','Checked transmitter under atmospheric condition'], result:'PV -1 kPa and 4.00 mA, no zero adjustment required.'},
  {id:'004', equipment:'111-MD01-PT4.1.01', category:'Pressure', title:'Blocked Access for Zero Check', issue:'Zero check could not be performed.', actions:['Checked field access','Found block valve hindered by pipe insulation','Requested modification confirmation to PIL'], result:'Follow-up required for insulation modification under block valve.'},
  {id:'005', equipment:'PO01-TT-151 / PO01-TT-149', category:'Temperature', title:'Thermocouple DCS Cross Assignment', issue:'New thermocouple showed ambient temperature while FCF was heating up.', actions:['Verified Type S thermocouple nameplate','Measured 4.0 mV output equivalent to approx. 500°C','Performed intermittent cable response test','Cross-checked tag plate and TT-149'], result:'Found cross assignment on DCS display; DCS engineering switching required.'},
  {id:'006', equipment:'111-AP03-DA1006', category:'Control Valve / MOV', title:'Damper Close Feedback Failure', issue:'No feedback on DCS when damper valve closed.', actions:['Checked 24 VDC in panel control box','Checked 24 VDC from PLC marshalling cabinet','Tested relay coil and continuity','Found bad continuity at relay pin 7/9','Swapped relay from DA1008'], result:'Close feedback appeared for DA1006; relay replacement recommended.'},
  {id:'007', equipment:'111CM01-WE1001F', category:'Weighing System', title:'Weight Feeder Remote Control Issue', issue:'Weight feeder could run from local but not remote from DCS.', actions:['Tested local/remote selector in main panel','Verified selector local cuts off 4–20 mA DCS signal to VSD AI2','Checked VSD I/O parameter','Verified local mode AI signal 0–10 VDC'], result:'Operation must ensure selector position; DCS mismatch indication recommended.'},
  {id:'008', equipment:'111-US01-CV1001', category:'Conveyor / Interlock', title:'DCS Allow Signal Missing', issue:'Allow did not appear and Local/DCS mode did not change.', actions:['Tested local/remote at field control panel','Verified relay Z-KA68 and PLC DI I2.2','Bypassed relay Z-KA3 chute down to activate permissive'], result:'Allow appeared at DCS; telescopic chute permissive modification/testing required.'},
  {id:'009', equipment:'111-SG02-TV002B', category:'Control Valve / MOV', title:'Control Valve No Response', issue:'Valve did not respond to DCS command.', actions:['Stroke checked 0–100% with no response','Tested positioner manual opening','Verified handwheel movement normal','Confirmed 4–20 mA command good','Inspected positioner regulator manifold','Adjusted regulator pressure from 0.4 to 0.5 MPa'], result:'Valve moved after pressure adjustment but slow response required PID/positioner review.'},
  {id:'010', equipment:'111-PO01-FT-US001/US002/003', category:'Flowmeter', title:'DP Flowmeter No Reading', issue:'Flowmeters could not read flow.', actions:['Checked transmitter output at 4 mA','Inspected HP and LP isolation valves','Found isolation valves closed','Normalized valve lineup'], result:'DP flow measurement restored after valve normalization.'},
  {id:'011', equipment:'111-PO01-WT001A', category:'Weighing System', title:'Weighing Transmitter Under Indication', issue:'DCS indication below zero.', actions:['Checked transmitter alarm and field display','Found out-limit under alarm','Checked analog connection','Measured analog output 2.0 mA','Restarted local panel power'], result:'Analog output recovered to 3.95 mA; display scaling confirmation required.'},
  {id:'012', equipment:'111-PF02-DA1001C', category:'Control Valve / MOV', title:'Damper Opening Error from 3-Phase Wiring', issue:'Opening damper valve error and abnormal noise.', actions:['Found 3-phase MCB off','Stroke tested local and DCS','Measured abnormal phase voltages','Electrical team found cross wiring between phase T and neutral','Rechecked voltage after correction'], result:'Voltage normalized and damper returned to normal without noise.'},
  {id:'013', equipment:'111CM01-DA1002A/E/H/I', category:'Control Valve / MOV', title:'Damper Overtorque Troubleshooting', issue:'Dampers could not operate due to overtorque indication.', actions:['Checked actual damper condition','Reset overtorque alarm','Travel tested open/close by handwheel','Adjusted close limit','Stroke tested local and remote'], result:'Dampers normalized; cleaning recommended due to hardened material buildup.'},
  {id:'014', equipment:'111-TS01-TT007A', category:'Temperature', title:'Type S Thermoelement Failure', issue:'Temperature transmitter error indication.', actions:['Checked transmitter and thermoelement termination','Checked marshalling fuse','Verified loop power 17.4 VDC','Simulated voltage injection to transmitter','Tested thermoelement continuity and mV output'], result:'All Type S double elements found broken; replacement required.'},
  {id:'015', equipment:'111AP03-LV001', category:'Control Valve / MOV', title:'Valve Could Not Fully Open', issue:'Valve stuck at 70% while full open command applied.', actions:['Checked actual valve position','Released handwheel to full open raised position','Tested close and open movement','Performed stroke test'], result:'Valve achieved 100% full open and stroke test OK.'},
  {id:'016', equipment:'111US03-CV1002/CV1003', category:'Conveyor / Interlock', title:'H Deviation Safety Signal Troubleshooting', issue:'Conveyor could not run even after DCS bypass during belt alignment.', actions:['Checked MCC and rack-out drawer','Checked IMS run from MCC','Verified H deviation signal still going to IMC','Disconnected H/L deviation safety signal cable','Restored cable after mechanical alignment'], result:'Conveyor test run OK; DCS bypass could not override hardwired signal.'},
  {id:'017', equipment:'111-TS02-TT006A', category:'Temperature', title:'Loose Thermocouple Connection', issue:'Temperature indication error.', actions:['Checked marshalling fuse','Verified loop power 17.4 VDC','Found loose cable from element to transmitter','Measured element output 1.04 mV on both elements','Checked transmitter setup with AMS Trex Type S'], result:'Connection normalized and temperature recovered around 170°C; datasheet update required from Type K to Type S.'},
  {id:'018', equipment:'381TC01-FT006', category:'Flowmeter', title:'Flowmeter Not Reading Due to Non-Full Pipe', issue:'Flowmeter read 0 m³/h while pump was running.', actions:['Checked flowmeter field reading','Verified parameter normal','Identified 3 inch pump line to 6 inch flowmeter line','Tested main pump 06A to fully fill pipe','Continued with pump 008'], result:'Flowmeter measured correctly after full pipe condition was achieved.'},
  {id:'019', equipment:'111US03-WT002', category:'Weighing System', title:'False Feedrate at No Load', issue:'Weight conveyor showed up to 7 TPH with no load.', actions:['Checked conveyor and weighing scale in running condition','Found material in weigher beam gap and support roller','Cleaned table of weigher','Rechecked load cell bolt tightness','Performed zero calibration'], result:'No-load feedrate normalized; PM cleaning schedule recommended.'},
  {id:'020', equipment:'111TC04-FT001', category:'Flowmeter', title:'Flowmeter Hunting Outside Range', issue:'Flowmeter measured -217.14 m³/h although range was 0–30 m³/h.', actions:['Confirmed no flow in pipeline','Observed hunting between 217 and -217 m³/h when flow applied','Checked parameters and faults','Attempted zero calibration','Inspected circuit board with PIL'], result:'Moisture/corrosion found on board; cleaning and retest required.'},
  {id:'021', equipment:'111US01-CV1001', category:'Conveyor / Interlock', title:'Pullcord Water Ingress False Trip', issue:'Conveyor tripper could not run with pullcord alarm although pullcords were released.', actions:['Rechecked all pullcord release/reset','Opened pullcord switches in outdoor area','Found two pullcords with water exposure','Cleaned body and contact switch','Tested contact function'], result:'Alarm reset OK after cleaning and functional test.'},
  {id:'022', equipment:'111-PO01-FV301', category:'Control Valve / MOV', title:'Feedback and Command Mismatch', issue:'Feedback 29% while command 8%.', actions:['Visual inspection at valve positioner','Reset positioner power by disconnecting cable','Checked handwheel condition','Found handwheel in manual operation','Switched handwheel from manual to auto','Tested DCS open command 30%'], result:'Feedback matched command at 30%; status finished.'},
  {id:'023', equipment:'111-PO01-FT301', category:'Flowmeter', title:'Fault F4 Flow Transmitter', issue:'High flow indication to 100% when control valve was small open.', actions:['Visual inspection at flowmeter','Found Fault F4 on field display','Reset 24 VDC power from marshalling cabinet','Compared Fault F4 with instruction manual'], result:'Fault remained; sensor replacement required, status pending.'},
  {id:'024', equipment:'Dip Stick Temperature FSF', category:'Temperature', title:'High Temperature Cable Replacement', issue:'Dip stick could not measure temperature.', actions:['Visual inspection found bad cable condition','Prepared new cable','Re-installed new cable','Monitored temperature indication'], result:'Display returned to normal around 1288°C.'},
  {id:'025', equipment:'111-PS01-FV1104B', category:'Control Valve / MOV', title:'Negative Valve Feedback Due to Power Loss', issue:'Feedback opening read -118% when valve command was 0%.', actions:['Found motorized valve field display off','Checked local control panel, no 220 VAC','Checked other instrument power status','Found Coriolis flowmeter display also off','Coordinated with electrical team','Found 220 VAC stopped at broken fuse'], result:'Fuse failure identified; pending spare fuse.'},
  {id:'026', equipment:'111-PS01-BU1104B', category:'Burner / Combustion', title:'220 VAC Short Circuit', issue:'220 VAC source for burner panel short circuit.', actions:['Found cable from local control panel to MOV power supply shorted','Tested using other cable simulation','Powered ON breaker with temporary cable'], result:'Breaker normal with replacement cable; permanent cable replacement and old cable investigation recommended.'},
  {id:'027', equipment:'111-PS01-BU1104B System', category:'Burner / Combustion', title:'LOP Short Circuit Isolation', issue:'Short circuit in Local Operation Panel.', actions:['Modified fuse to double 6A circuit breaker for troubleshooting','Separated 220 VAC source for DC power supply, relay and MOV','Connected loads one by one','Breaker tripped when MOV cable connected','Checked resistance and insulation','Pulled temporary cable'], result:'MOV operated from DCS and stroke check OK; permanent cable required.'},
  {id:'028', equipment:'Anode Furnace 2 Flame Detector', category:'Burner / Combustion', title:'Flame Indication Mismatch', issue:'HMI flame indication OFF while local flame indication ON.', actions:['Checked local flame indication','Checked flame relay ON','Verified PLC digital input lamp ON','Tried bypass indication from AF1/AF2 HMI graphic','Found AF1 bypass could operate AF2 control system'], result:'Pending internal HMI/PLC program check.'},
  {id:'029', equipment:'Oxygen Gas Detector CH2', category:'Analyzer / Gas Detector', title:'Oxygen Sensor Failure', issue:'Low alarm with oxygen indication 0.0%.', actions:['Inspected sensor','Tested CH2 transmitter with CH3 oxygen sensor','Tested CH2 sensor on CH3 transmitter'], result:'CH2 transmitter normal, CH2 sensor broken; replacement required.'},
  {id:'030', equipment:'111-CG01-FV001A2', category:'Control Valve / MOV', title:'Control Valve Cannot Fully Close', issue:'Water supply to granulation valve could not fully close.', actions:['Found positioner bracket bolt loose','Found actuator bolts loose','Removed and fixed positioner','Retightened actuator bolts','Stroke checked 0–100%'], result:'Valve returned to normal; status finished.'},
  {id:'031', equipment:'111-TS01-TT007A/B & TT006A/B', category:'Temperature', title:'Multiple Thermoelement Replacement', issue:'Thermoelements required replacement.', actions:['Prepared site and material','Found need reducer coupling 1 inch to 1/2 inch','Prepared four reducer couplings','Sized new thermoelements','Replaced elements one by one','Changed transmitter element type from K to S','Checked site and DCS indication'], result:'Replacement completed; Type S cable and thermowell observations noted.'},
  {id:'032', equipment:'111PS01-WE1001 A1/A2/B1/B2', category:'Pressure', title:'Pressure Switch Low Reading Investigation', issue:'Pressure switch reading low or below set point.', actions:['Checked A1 history leakage on sensor body','Swapped A1 with A2 to validate pressure','Compared inlet/outlet pressure on dome valve','Identified low outlet pressure to sensor on B1'], result:'Instrument A1 leakage and possible dome valve seal/dust issue identified.'},
  {id:'033', equipment:'111-TS01-HV002', category:'Control Valve / MOV', title:'New Control Valve Replacement Preparation', issue:'Preparation for new control valve installation.', actions:['Measured new valve flange-to-flange 340 mm','Measured old valve flange-to-flange 370 mm','Coordinated installation area with mechanical team','Prepared cable route sketch and BOM','Collected material','Fabricated roundbox support','Prepared instrument air line and cable pulling'], result:'Instrument side preparation finished; waiting valve installation and tie-in.'},
  {id:'034', equipment:'111-PS01-FA1001AZ', category:'Rotating Equipment', title:'Fan Instrumentation Support', issue:'Mechanical support job for fan instrumentation.', actions:['Visual inspection of fan instrumentation','Installed two temperature elements at DE/NDE shaft','Installed two vibration sensors at DE/NDE shaft','Stroke checked damper actuator 0–100%'], result:'Instrumentation support completed; bent damper lever observed.'},
  {id:'035', equipment:'111-TS02-TT008A', category:'Temperature', title:'Transmitter and Thermoelement Failure', issue:'Temperature indication error.', actions:['Visual inspection','Checked terminal voltage 16.98 VDC','Checked marshalling voltage 17.07 VDC','Disconnected transmitter signal and voltage recovered to 22.77 VDC','Measured sensor output -115.2 mV'], result:'Temperature transmitter and thermoelement were bad; replacement required. WO 110000683395.'},
  {id:'036', equipment:'111-PF02-BU1001-BO04', category:'Burner / Combustion', title:'Burner Flame Rod Replacement', issue:'Flame off caused by broken flame rod.', actions:['Inspected rods','Removed old flame rod','Installed new flame rod','Set oxygen and natural gas pressure','Re-ignited burner'], result:'Flame ON and good. WO 110000683209.'},
  {id:'037', equipment:'111-PS01-BU1103C', category:'Burner / Combustion', title:'Flame Scanner Replacement', issue:'No flame signal at DCS and bypass condition.', actions:['Prepared spare flame scanner','Stopped NG and combustion line','Powered OFF local panel','Removed flame scanner','Disconnected and remarked cable','Installed new scanner','Re-ignited burner'], result:'Flame signal good; status done. WO 110000683651.'},
  {id:'038', equipment:'111AG91-FT103', category:'Flowmeter', title:'Flow Reading with Valves Closed', issue:'Flowmeter showed flow while shutoff valve and control valve were closed.', actions:['Verified actual reading 186.46 Nm³/h','Closed manual valve before control valve and reading became zero','Forced close control valve from positioner','Adjusted stopper for closed control valve to 0%','Adjusted shutoff valve close stopper'], result:'Flowmeter reading became 0 Nm³/h and leakage monitoring normal.'},
  {id:'039', equipment:'111-PS01-BU1102', category:'Burner / Combustion', title:'Ignitor Cable and Rod Failure', issue:'Ignitor cable broken and burner no spark.', actions:['Inspected ignitor cable','Removed old connector','Checked transformer 220 VAC source at 230 VAC','Checked relay operation','Removed ignitor rod','Found broken end bolt','Cleaned and reassembled rod','Re-ignited'], result:'Spark appeared in middle chamber but alarm remained; spare rod replacement and night shift handover required. WO 110000684224.'},
  {id:'040', equipment:'111-AP03-AT001', category:'Analyzer / Gas Detector', title:'Analyzer Indication Stuck', issue:'DCS operator reported analyzer indication stuck.', actions:['Visual inspection with PIL instrument','Checked alarm and found concentration under range','Checked transmitter parameters','Ensured upstream and downstream block valves open','Reset 220 VAC power','Changed Inst Factor from 1.000 to 3.000 for test'], result:'PIL needed comparison with laboratory concentration and conductivity sampling. WO 110000686011.'},
  {id:'041', equipment:'111-PS01-BU1105B', category:'Burner / Combustion', title:'No Flame Troubleshooting', issue:'Burner no flame.', actions:['Connected ignitor cable','Ignition failed due to NG pressure above 70 kPa','Regulator adjuster issue found','Throttled main NG block valve','Removed and inspected ignitor','Found broken and dirty ignitor end','Replaced ignitor','Flame OK but scanner did not read','Inspected scanner glass dust','Replaced flame scanner'], result:'Re-ignite successful; flame ON and status finished.'},
  {id:'042', equipment:'111-SG03-AT002', category:'Analyzer / Gas Detector', title:'SO₂ Sampling System Maintenance', issue:'Replace metal filter and top sampling filter.', actions:['Recorded rotameter 1 L/min and SO₂ 0% before cleaning','Powered OFF blowback PLC','Opened cover flange','Replaced metal filter','Inspected sampling nozzle','Replaced teflon filter','Cleaned SO₂ dust','Normalized blowback PLC'], result:'Flowrate increased to 1.3 L/min and SO₂ indication stable at 0%; status finished.'},
  {id:'043', equipment:'111-TS01-PT009', category:'Pressure', title:'Plugged Nozzle Pressure Indication', issue:'Incorrect pressure indication.', actions:['Zero checked transmitter in atmosphere condition PV -1.87 Pa / error -0.143%','Removed impulse pipe nozzle flange','Found plugged nozzle','Deplugged nozzle','Vacuum checked good','Reinstalled flange'], result:'Pressure indication recovered to -132 Pa. Notification 110000689354.'},
  {id:'044', equipment:'SG01-EP1001', category:'Temperature', title:'RTD Temperature Transmitter Check', issue:'Temperature transmitter verification.', actions:['Measured RTD resistance','Disconnected termination','Checked and ensured no crack','Measured sensor condition good','Reinstalled sensor'], result:'DCS reading confirmed normal.', media:[{type:'image', src:'assets/case-rtd-sg01-ep1001.jpg', caption:'RTD element and terminal inspection'}]},
  {id:'045', equipment:'111PF02-FU1001B', category:'Pneumatic System', title:'Skimming Mouth Cannot Fully Open', issue:'Skimming mouth could not fully open.', actions:['Checked opening performance','Inspected and cleaned silencer','Tested without silencer and actuator could fully open','Found regulator pressure gauge not measuring','Replaced regulator','Observed silencer continuously venting air'], result:'Indicated pneumatic air cylinder leak; mechanical team requested operation without silencer. Notification 110000898477.', media:[{type:'image', src:'assets/case-pneumatic-skimming-mouth.jpg', caption:'Pneumatic regulator / silencer troubleshooting documentation'}]},
  {id:'046', equipment:'Masoneilan Control Valve Positioner', category:'Control Valve / MOV', title:'Masoneilan Positioner Calibration Documentation', issue:'Calibration and setup documentation for Masoneilan valve positioner.', actions:['Performed/observed positioner calibration workflow','Verified valve positioner response during calibration','Documented control valve calibration activity','Used as technical evidence for control valve and positioner exposure'], result:'Video documentation added as portfolio evidence for control valve positioner calibration activity.', media:[{type:'video', src:'assets/masoneilan-positioner-calibration.mp4', caption:'Masoneilan positioner calibration video'},{type:'image', src:'assets/case-masoneilan-photo.jpg', caption:'Masoneilan / Valve 4 reference documentation'}]}


];
